### ISSUE TITLE
Unable to process example files

### ISSUE THREAD

**Issue by kevinkovalchik** [optimusmoose/XNet#1]
Hello,

I am interested in your tool, but have been unable to get it running. I am using a Windows 10 system with JDK 8 update 181 installed. Following the readme instructions, from within the "target" directory I invoked the following:
`java -jar xnet-1.0.jar good_example.csv`
and get the following exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.koloboke.collect.map.hash.HashFloatDoubleMaps.getDefaultFactory(HashFloatDoubleMaps.java:54)
        at com.koloboke.collect.map.hash.HashFloatDoubleMaps.newMutableMap(HashFloatDoubleMaps.java:78)
        at edu.msViz.xnet.dataTypes.IsotopeTrace.computeArc(IsotopeTrace.java:157)
        at edu.msViz.xnet.dataTypes.IsotopeTrace.<init>(IsotopeTrace.java:128)
        at edu.msViz.xnet.dataTypes.TracesBundle.lambda$synthesize$0(TracesBundle.java:63)
        at java.util.HashMap$KeySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at edu.msViz.xnet.dataTypes.TracesBundle.synthesize(TracesBundle.java:61)
        at edu.msViz.xnet.TestRun.main(TestRun.java:30)
Caused by: java.util.NoSuchElementException
        at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
        at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
        at java.util.ServiceLoader$1.next(Unknown Source)
        at com.koloboke.collect.map.hash.HashFloatDoubleMaps$DefaultFactoryHolder.<clinit>(HashFloatDoubleMaps.java:39)
        ... 9 more
```

I thought perhaps this was an issue with the build and my system not being compatible, so I tried building it from source. This also threw an exception:

```
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------------< edu.msViz:xnet >---------------------------
[INFO] Building xnet 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for org.eclipse.recommenders:org.eclipse.recommenders.jayes:jar:2.6.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.238 s
[INFO] Finished at: 2019-02-21T15:31:12-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xnet: Could not resolve dependencies for project edu.msViz:xnet:jar:1.0: Could not find artifact org.eclipse.recommenders:org.eclipse.recommenders.jayes:jar:2.6.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

Thanks for any advice you can provide.

Kevin

**Comment by optimusmoose** [comment]
Taking a look...

**Comment by optimusmoose** [comment]
Hey Kevin, it looks like there are issues with the remote pull of the
dependencies in windows. I have someone taking a look. In the meantime,
we've put a new .jar file in the repo that has everything you need compiled
into it. If you'd like to run it in the meantime, give it a shot.

Thanks,
Rob

**Comment by kevinkovalchik** [comment]
Great, thanks!

**Comment by kevinkovalchik** [comment]
Yes, that .jar file is working fine in windows.

Thanks,
Kevin
